### ISSUE TITLE
iterable.length has been deprecated, use iterable.size or iterable.count(). This warning will become a silent error in a future version. Error

### ISSUE THREAD

**Issue by bkniffler** [ianstormtaylor/slate#1149]
This seems to be an issue with current immutableJS version. iterable.length is used in many places in slate, for example `slate/src/models/history.js`.

```
iterable.length has been deprecated, use iterable.size or iterable.count(). This warning will become a silent error in a future version. Error
    at Stack.get (webpack-internal:///./node_modules/immutable/dist/immutable.js:4650:21)
    at History.save (webpack-internal:///./node_modules/slate/lib/models/history.js:123:16)
    at Change.applyOperation (webpack-internal:///./node_modules/slate/lib/models/change.js:136:27)
    at Changes.splitNodeByKey (webpack-internal:///./node_modules/slate/lib/changes/by-key.js:516:10)
    at Change.call (webpack-internal:///./node_modules/slate/lib/models/change.js:180:10)
    at Change.(anonymous function) [as splitNodeByKey] (webpack-internal:///./node_modules/slate/lib/models/change.js:254:15)
    at eval (webpack-internal:///./node_modules/slate/lib/changes/by-key.js:565:12)
    at List.__iterate (webpack-internal:///./node_modules/immutable/dist/immutable.js:2194:13)
    at List.forEach (webpack-internal:///./node_modules/immutable/dist/immutable.js:4374:19)
    at Changes.splitDescendantsByKey (webpack-internal:///./node_modules/slate/lib/changes/by-key.js:561:9)
```

**Comment by winfield** [comment]
Older version of immutable has this warning, which is removed in immutable@3.8.0. 
immutable is now a peer dependency of slate([detail here](https://github.com/ianstormtaylor/slate/pull/1106)), try installing it to you dependency.
