### ISSUE TITLE
TypeError: Cannot read property 'nodes' of undefined for unwrapNodeByKey in normalize

### ISSUE THREAD

**Issue by alanctkc** [ianstormtaylor/slate#1203]
I've been fighting `unwrapNodeByKey` in a rule normalize function for a bit, and I'm starting to wonder if there may be some underlying issue.

I was expecting that if I called `change.unwrapNodebyKey()` in a normalize function with a node key, the node's parent would be replaced with the node itself, but instead, the editor errors out with a console trace.

Maybe something with deleting/replacing a parent node and the normalization process expecting the parent node's reference and child nodes to still be intact? Operations that delete child nodes don't have an issue.

It's also possible I'm just misunderstanding how to use the method. :)

Here's a codepen with it whittled down to the basics:

https://codepen.io/alanct/pen/PJOZBb

In the repro, there's an `outer` block (red) and an `inner` block (blue). Whenever a character is entered in the inner block, a rule catches it, deletes the character, and attempts to unwrap the inner block. Here's the trace:

```
react-dom.min.js:14 Uncaught TypeError: Cannot read property 'nodes' of undefined
    at _loop (https://unpkg.com/slate@0.24.6/dist/slate.js:9182:11)
    at normalizeNodeAndChildren (https://unpkg.com/slate@0.24.6/dist/slate.js:9190:5)
    at _loop (https://unpkg.com/slate@0.24.6/dist/slate.js:9168:7)
    at normalizeNodeAndChildren (https://unpkg.com/slate@0.24.6/dist/slate.js:9190:5)
    at Changes.normalizeNodeByKey (https://unpkg.com/slate@0.24.6/dist/slate.js:9131:3)
    at Change.call (https://unpkg.com/slate@0.24.6/dist/slate.js:10365:10)
    at Change.(anonymous function) [as normalizeNodeByKey] (https://unpkg.com/slate@0.24.6/dist/slate.js:10439:15)
    at Changes.normalizeDocument (https://unpkg.com/slate@0.24.6/dist/slate.js:9110:10)
    at Change.call (https://unpkg.com/slate@0.24.6/dist/slate.js:10365:10)
    at Change.(anonymous function) [as normalizeDocument] (https://unpkg.com/slate@0.24.6/dist/slate.js:10439:15)
```

I'm in latest Chrome on Arch Linux, Slate 0.24.6.

**Comment by alanctkc** [comment]
I'm actually noticing that in some instances `unwrapNodeByKey` is succeeding for me. It seems to never happen when it's the first block in the document. I'm also seeing some kind of behavior I can't pinpoint-- like if the block needs to be unwrapped more times than the depth of the previous sibling block that has nested nodes, it fails (consistent with the first-block-fails behavior). May try to work on repros of those scenarios as well in a fiddle.

**Comment by zhujinxuan** [comment]
I think it is fixed by https://github.com/ianstormtaylor/slate/pull/1538

**Comment by intellild** [comment]
Same problem.
I figured out that is is cause by elements with out child text node.
Currently I ignore specific elements without text when deserializing to work around.
