### ISSUE TITLE
Syntax Highlighting Example is Broken

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#1368]
#### Do you want to request a *feature* or report a *bug*?

bug

#### What's the current behavior?

There is no Syntax Highlighting in the Demo at this URL:

http://slatejs.org/#/code-highlighting

If you change the syntax highlighting selection to any other selection like `HTML` then it shows this error:

```
An error was thrown by one of the example's React components!

TypeError: Cannot read property 'text' of undefined
    at Object.a.decorateNode (http://slatejs.org/build.prod.js:143:3658)
    at Object.onChange.t.schema.o.(anonymous function) [as decorateNode] (http://slatejs.org/build.prod.js:4998:6030)
    at t.value (http://slatejs.org/build.prod.js:5150:1790)
    at t.value (http://slatejs.org/build.prod.js:5141:5788)
    at t.e.(anonymous function) [as getDecorations] (http://slatejs.org/build.prod.js:5175:710)
    at t.renderNode (http://slatejs.org/build.prod.js:5004:4419)
    at http://slatejs.org/build.prod.js:5004:2670
    at Array.map (<anonymous>)
    at t.value (http://slatejs.org/build.prod.js:5004:2612)
    at u (http://slatejs.org/build.prod.js:4810:19025)

    in t
    in div
    in t
    in t
    in div
    in t
    in e
    in t
    in div
    in div
    in t
    in e
    in t
```

#### What's the expected behavior?

When I first view the page, the text is syntax highlighted as per the selection (JavaScript by default).

If I change the selection, the text will be highlighted with the appropriate syntax highlighter and will not throw an error.

**Comment by eliecerthoms** [comment]
Note that it also breaks  when inputting `new` followed by a space and a capital letter 
as in `new Image`, it will break as soon as the capital 'i' is inserted.

**Comment by kashifimran** [comment]
@ianstormtaylor This bug also appears when you paste something in a fully empty editor (no content) and then execute undo (e.g. ctrl+z). It can be replicated in http://slatejs.org/#/plain-text
