### ISSUE TITLE
Pasting to an empty document and then undoing results in an error

### ISSUE THREAD

**Issue by optimistiks** [ianstormtaylor/slate#1448]
#### Do you want to request a *feature* or report a *bug*?

Bug

#### What's the current behavior?

When pasting anything to an empty document and then undoing, an error occurs:
```
Uncaught Error: Invalid `key` argument! It must be a key string, but you passed: null
    at assertKey (https://npmcdn.com/slate@0.31.5/dist/slate.js:14526:9)
    at Document.getFurthestAncestor (https://npmcdn.com/slate@0.31.5/dist/slate.js:13109:13)
    at Document.object.(anonymous function) [as getFurthestAncestor] (https://npmcdn.com/slate@0.31.5/dist/slate.js:19604:30)
    at Document.getSelectionIndexes (https://npmcdn.com/slate@0.31.5/dist/slate.js:13818:26)
    at Content.render (https://npmcdn.com/slate-react@0.10.20/dist/slate-react.js:8786:30)
```
Issue can be reproduced on the default fiddle: [https://jsfiddle.net/fj9dvhom/1/](https://jsfiddle.net/fj9dvhom/1/)
Here is a gif: [https://imgur.com/a/FWwGo](https://imgur.com/a/FWwGo)

#### What's the expected behavior?

Undo should work without any errors

**Comment by conorcussell** [comment]
![undo](https://user-images.githubusercontent.com/4960622/35920272-582c6322-0c0f-11e8-9c45-7c9760fc6ce8.gif)

This is no longer an issue, (probably) fixed by https://github.com/ianstormtaylor/slate/pull/1443
