### ISSUE TITLE
Normalization Infinity Loop

### ISSUE THREAD

**Issue by ch1ll0ut1** [ianstormtaylor/slate#1511]
#### Do you want to request a *feature* or report a *bug*?
Bug

#### What's the current behavior?
Chrome, Slate 0.30.6, SlateReact 0.10.11, 

I encounter an infinity loop in several situation, i will explain one of them below.

I have 3 blocks:
- List
- List Item
- Image

In my editor i have a List with a empty item. Then i drop an image from the editor to the empty list item. Then the normalization kicks in with "child_type_invalid" it is supposed to unwrap the image from the List so that document becomes the parent of the image.

The normalization schema (in typescript):
```javascript
      blocks: {
        'numbered-list-item': {
          nodes: [{ objects: ['text'] }],
          parent: { types: ['numbered-list'] },
          normalize: (change: Change, reason: string, context: NormalizeContext) => {
            switch (reason) {
              case 'parent_type_invalid': {
                return change.wrapBlock('numbered-list');
              }
            }
            return;
          },
        },
        'bulleted-list-item': {
          nodes: [{ objects: ['text'] }],
          parent: { types: ['bulleted-list'] },
          normalize: (change: Change, reason: string, context: NormalizeContext) => {
            switch (reason) {
              case 'parent_type_invalid': {
                return change.wrapBlock('bulleted-list');
              }
            }
            return;
          },
        },
        'numbered-list': {
          nodes: [{ types: ['numbered-list-item'], min: 1 }],
          normalize: (change: Change, reason: string, context: NormalizeContext) => {
            switch (reason) {
              case 'child_type_invalid': {
                return change.unwrapBlock('numbered-list');
              }
            }
            return;
          },
        },
        'bulleted-list': {
          nodes: [{ types: ['bulleted-list-item'], min: 1 }],
          normalize: (change: Change, reason: string, context: NormalizeContext) => {
            switch (reason) {
              case 'child_type_invalid': {
                return change.unwrapBlock('bulleted-list');
              }
            }
            return;
          },
        },
      },
```

I have a test case written in hyperscript to try to reproduce that (and also tried to reproduce it in fiddle) but the infitiny loop doesnt happen there.

```javascript
test('handle image', async () => {
  const plugin = Plugin();
  const schema = Schema.create(plugin.schema);

  // @ts-ignore
  const input: Value = (
    <value>
      <document>
        <numbered_list>
          <image />
        </numbered_list>
      </document>
    </value>
  );

  // @ts-ignore
  const output: Value = (
    <value>
      <document>
        <image />
      </document>
    </value>
  );

  isEqual(input, output, schema);
});
```

Slate Log:
Start of drop and infinity loop: https://imgur.com/a/y08mE
End of loop: https://imgur.com/a/G1fUS

#### What's the expected behavior?
It is supposed to work in the browser like in the test case.

**Comment by CameronAckermanSEL** [comment]
(It's kinda hard to read your code snippet so I may be mistaken.)

I'm pretty sure the issue you are having is that the schema normalize routine is not able to successfully unwrap the image from the list because  `change.unwrapBlock('numbered-list'); ` relies on the image block being in the selected range, which will often be true but at this layer is not guaranteed. Instead, you might be able to get it to work using `change.unwrapNodeByKey(child.key)` or `change.unwrapBlockByKey(child.key, 'numbered-list')`

**Comment by ch1ll0ut1** [comment]
Sry, I updated the code formatting.

I tried your suggested solutions bot got the same result in both cases.

**Comment by CameronAckermanSEL** [comment]
Oh these rules have a little more to them. Have you tried logging the `reason` to the console to see what rule it's looping on? There are a number of rules in the schema that the current implementation does not seem to be normalizing explicitly and the core slate schema rules may also not be handling them.

**Comment by ch1ll0ut1** [comment]
The following rule is triggers with child_type_invalid

```javascript
'numbered-list': {
          nodes: [{ types: ['numbered-list-item'], min: 1 }],
          normalize: (change: Change, reason: string, context: NormalizeContext) => {
            switch (reason) {
              case 'child_type_invalid': {
                const { child, node } = context;

                if (child) {
                  if (child.type === 'list-item') {
                    return change.setNodeByKey(child.key, 'numbered-list-item');
                  }

                  return change.unwrapBlockByKey(node.key, 'numbered-list-item');
                }
              }
            }
            return;
          },
        },
```

and the context of:

```javascript
{
    node: Block { data: Map {}, isVoid: false, key: "8", nodes: List[Block { data: Map {}, isVoid: false, key: "5", nodes: List[Block { data: Map {}, isVoid: false, key: "2", nodes: List[Text { characters: List[Character { marks: Set {}, text: "t" }, Character { marks: Set {}, text: "e" }, Character { marks: Set {}, text: "x" }, Character { marks: Set {}, text: "t" }], key: "1" }], type: "numbered-list-item" }], type: "numbered-list" }], type: "numbered-list" },
    rule: {
        data: {},
        isVoid: null,
        nodes: [
            [Object]
        ],
        first: null,
        last: null,
        parent: null,
        text: null,
        normalize: [Function: normalize]
    },
    child: Block { data: Map {}, isVoid: false, key: "5", nodes: List[Block { data: Map {}, isVoid: false, key: "2", nodes: List[Text { characters: List[Character { marks: Set {}, text: "t" }, Character { marks: Set {}, text: "e" }, Character { marks: Set {}, text: "x" }, Character { marks: Set {}, text: "t" }], key: "1" }], type: "numbered-list-item" }], type: "numbered-list" },
    index: 0
}
```

in the test case of:

```javascript
test('do not allow nested lists', async () => {
  // @ts-ignore
  const input: Value = (
    <value>
      <document>
        <numbered_list>
          <numbered_list>
            <numbered_list_item>text</numbered_list_item>
          </numbered_list>
        </numbered_list>
      </document>
    </value>
  );

  // @ts-ignore
  const output: Value = (
    <value>
      <document>
        <numbered_list>
          <numbered_list_item>text</numbered_list_item>
        </numbered_list>
      </document>
    </value>
  );

  isEqual(input, output, schema);
});
```

The "child_type_invalid" is infinitive.

**Comment by ch1ll0ut1** [comment]
stacktrace:


  ● should not allow nested lists

    RangeError: Maximum call stack size exceeded
      
      at Block.toJSON (node_modules/slate/lib/models/block.js:88:20)
          at JSON.stringify (<anonymous>)
      at quoteString (node_modules/immutable/dist/immutable.js:1922:17)
      at Block.toString (node_modules/immutable/dist/immutable.js:5413:41)
      at Block.Object.<anonymous>.RecordPrototype.inspect.RecordPrototype.toSource (node_modules/immutable/dist/immutable.js:5531:15)
      at formatValue (util.js:430:38)
      at formatProperty (util.js:833:11)
      at formatObject (util.js:649:17)
      at formatValue (util.js:609:18)
      at inspect (util.js:324:10)
      at format (util.js:253:18)
      at Object.normalize (src/features/WikiEditor/plugins/List/plugin.tsx:46:21)
      at node_modules/slate/lib/models/schema.js:177:34
      at iterate (node_modules/slate/lib/changes/with-schema.js:163:5)
      at normalizeNode (node_modules/slate/lib/changes/with-schema.js:184:3)
      at normalizeNodeAndChildren (node_modules/slate/lib/changes/with-schema.js:126:5)
      at _loop (node_modules/slate/lib/changes/with-schema.js:99:7)
      at normalizeNodeAndChildren (node_modules/slate/lib/changes/with-schema.js:121:5)
      at Object.<anonymous>.Changes.normalizeNodeByKey (node_modules/slate/lib/changes/with-schema.js:54:3)
      at Change.call (node_modules/slate/lib/models/change.js:176:10)
      at Change.(anonymous function) [as normalizeNodeByKey] (node_modules/slate/lib/models/change.js:235:15)
      at Object.<anonymous>.Changes.normalizeDocument (node_modules/slate/lib/changes/with-schema.js:37:10)
      at Change.call (node_modules/slate/lib/models/change.js:176:10)
      at Change.(anonymous function) [as normalizeDocument] (node_modules/slate/lib/models/change.js:235:15)
      at Object.<anonymous>.Changes.unwrapBlockAtRange (node_modules/slate/lib/changes/at-range.js:1241:12)
      at Change.call (node_modules/slate/lib/models/change.js:176:10)
      at Change.(anonymous function) [as unwrapBlockAtRange] (node_modules/slate/lib/models/change.js:235:15)
      at Object.<anonymous>.Changes.unwrapBlockByKey (node_modules/slate/lib/changes/by-key.js:664:10)
      at Change.call (node_modules/slate/lib/models/change.js:176:10)
      at Change.(anonymous function) [as unwrapBlockByKey] (node_modules/slate/lib/models/change.js:235:15)
      at Object.normalize (src/features/WikiEditor/plugins/List/plugin.tsx:56:33)
      at node_modules/slate/lib/models/schema.js:177:34
      at iterate (node_modules/slate/lib/changes/with-schema.js:163:5)
      at normalizeNode (node_modules/slate/lib/changes/with-schema.js:184:3)
      at normalizeNodeAndChildren (node_modules/slate/lib/changes/with-schema.js:126:5)
      at _loop (node_modules/slate/lib/changes/with-schema.js:99:7)
      at normalizeNodeAndChildren (node_modules/slate/lib/changes/with-schema.js:121:5)
      at Object.<anonymous>.Changes.normalizeNodeByKey (node_modules/slate/lib/changes/with-schema.js:54:3)
      at Change.call (node_modules/slate/lib/models/change.js:176:10)
      at Change.(anonymous function) [as normalizeNodeByKey] (node_modules/slate/lib/models/change.js:235:15)
      at Object.<anonymous>.Changes.normalizeDocument (node_modules/slate/lib/changes/with-schema.js:37:10)
      at Change.call (node_modules/slate/lib/models/change.js:176:10)
      at Change.(anonymous function) [as normalizeDocument] (node_modules/slate/lib/models/change.js:235:15)
      at Object.<anonymous>.Changes.unwrapBlockAtRange (node_modules/slate/lib/changes/at-range.js:1241:12)
      at Change.call (node_modules/slate/lib/models/change.js:176:10)
      at Change.(anonymous function) [as unwrapBlockAtRange] (node_modules/slate/lib/models/change.js:235:15)
      at Object.<anonymous>.Changes.unwrapBlockByKey (node_modules/slate/lib/changes/by-key.js:664:10)
      at Change.call (node_modules/slate/lib/models/change.js:176:10)
      at Change.(anonymous function) [as unwrapBlockByKey] (node_modules/slate/lib/models/change.js:235:15)
      at Object.normalize (src/features/WikiEditor/plugins/List/plugin.tsx:56:33)
      at node_modules/slate/lib/models/schema.js:177:34
      at iterate (node_modules/slate/lib/changes/with-schema.js:163:5)
      at normalizeNode (node_modules/slate/lib/changes/with-schema.js:184:3)
      at normalizeNodeAndChildren (node_modules/slate/lib/changes/with-schema.js:126:5)
      at _loop (node_modules/slate/lib/changes/with-schema.js:99:7)
      at normalizeNodeAndChildren (node_modules/slate/lib/changes/with-schema.js:121:5)
      at Object.<anonymous>.Changes.normalizeNodeByKey (node_modules/slate/lib/changes/with-schema.js:54:3)
      at Change.call (node_modules/slate/lib/models/change.js:176:10)
      at Change.(anonymous function) [as normalizeNodeByKey] (node_modules/slate/lib/models/change.js:235:15)
      at Object.<anonymous>.Changes.normalizeDocument (node_modules/slate/lib/changes/with-schema.js:37:10)
      at Change.call (node_modules/slate/lib/models/change.js:176:10)
      at Change.(anonymous function) [as normalizeDocument] (node_modules/slate/lib/models/change.js:235:15)
      at Object.<anonymous>.Changes.unwrapBlockAtRange (node_modules/slate/lib/changes/at-range.js:1241:12)
      at Change.call (node_modules/slate/lib/models/change.js:176:10)
      at Change.(anonymous function) [as unwrapBlockAtRange] (node_modules/slate/lib/models/change.js:235:15)
      at Object.<anonymous>.Changes.unwrapBlockByKey (node_modules/slate/lib/changes/by-key.js:664:10)
      at Change.call (node_modules/slate/lib/models/change.js:176:10)
      at Change.(anonymous function) [as unwrapBlockByKey] (node_modules/slate/lib/models/change.js:235:15)
      at Object.normalize (src/features/WikiEditor/plugins/List/plugin.tsx:56:33)
      at node_modules/slate/lib/models/schema.js:177:34
      at iterate (node_modules/slate/lib/changes/with-schema.js:163:5)
      at normalizeNode (node_modules/slate/lib/changes/with-schema.js:184:3)
      at normalizeNodeAndChildren (node_modules/slate/lib/changes/with-schema.js:126:5)
      at _loop (node_modules/slate/lib/changes/with-schema.js:99:7)
      at normalizeNodeAndChildren (node_modules/slate/lib/changes/with-schema.js:121:5)
      at Object.<anonymous>.Changes.normalizeNodeByKey (node_modules/slate/lib/changes/with-schema.js:54:3)
      at Change.call (node_modules/slate/lib/models/change.js:176:10)
      at Change.(anonymous function) [as normalizeNodeByKey] (node_modules/slate/lib/models/change.js:235:15)
      at Object.<anonymous>.Changes.normalizeDocument (node_modules/slate/lib/changes/with-schema.js:37:10)
      at Change.call (node_modules/slate/lib/models/change.js:176:10)
      at Change.(anonymous function) [as normalizeDocument] (node_modules/slate/lib/models/change.js:235:15)
      at Object.<anonymous>.Changes.unwrapBlockAtRange (node_modules/slate/lib/changes/at-range.js:1241:12)
      at Change.call (node_modules/slate/lib/models/change.js:176:10)
      at Change.(anonymous function) [as unwrapBlockAtRange] (node_modules/slate/lib/models/change.js:235:15)
      at Object.<anonymous>.Changes.unwrapBlockByKey (node_modules/slate/lib/changes/by-key.js:664:10)
      at Change.call (node_modules/slate/lib/models/change.js:176:10)
      at Change.(anonymous function) [as unwrapBlockByKey] (node_modules/slate/lib/models/change.js:235:15)
      at Object.normalize (src/features/WikiEditor/plugins/List/plugin.tsx:56:33)
      at node_modules/slate/lib/models/schema.js:177:34
      at iterate (node_modules/slate/lib/changes/with-schema.js:163:5)
      at normalizeNode (node_modules/slate/lib/changes/with-schema.js:184:3)
      at normalizeNodeAndChildren (node_modules/slate/lib/changes/with-schema.js:126:5)
      at _loop (node_modules/slate/lib/changes/with-schema.js:99:7)
      at normalizeNodeAndChildren (node_modules/slate/lib/changes/with-schema.js:121:5)
      at Object.<anonymous>.Changes.normalizeNodeByKey (node_modules/slate/lib/changes/with-schema.js:54:3)
      at Change.call (node_modules/slate/lib/models/change.js:176:10)
      at Change.(anonymous function) [as normalizeNodeByKey] (node_modules/slate/lib/models/change.js:235:15)
      at Object.<anonymous>.Changes.normalizeDocument (node_modules/slate/lib/changes/with-schema.js:37:10)
      at Change.call (node_modules/slate/lib/models/change.js:176:10)

**Comment by CameronAckermanSEL** [comment]
@ch1ll0ut1 I think this is a mistake in the normalize function.

For `numbered-list` there's this rule:
```
'numbered-list': {
          nodes: [{ types: ['numbered-list-item'], **min: 1** }],
```

Which will trigger the `child_type_invalid` schema violation. I don't see anywhere in the normalization function where this is being resolved, so it is very likely that it's looping infinitely because the `min: 1` rule is never satisfied.

**Comment by zhujinxuan** [comment]
It is because `unwrapBlock` is `unwrapBlockAtRange(value.selection)`. 

You should:
```
  change.unwrapNodeByKey(child.key, { normalize: false });
```

**Comment by ch1ll0ut1** [comment]
@zhujinxuan i tried unwrapNodeByKey before too (without normalizing set to false) and it had the same result. I just tried it again setting normalizing to false and getting a new error:

```javascript
 TypeError: Cannot read property 'nodes' of null
      
      at Object.<anonymous>.Changes.unwrapNodeByKey (node_modules/slate/lib/changes/by-key.js:707:34)
      at Change.call (node_modules/slate/lib/models/change.js:197:10)
      at Change.(anonymous function) [as unwrapNodeByKey] (node_modules/slate/lib/models/change.js:262:15)
      at Object.normalize (src/features/WikiEditor/plugins/List/plugin.tsx:66:33)
      at node_modules/slate/lib/models/schema.js:201:34
      at iterate (node_modules/slate/lib/changes/with-schema.js:159:5)
      at normalizeNode (node_modules/slate/lib/changes/with-schema.js:182:3)
      at normalizeNodeAndChildren (node_modules/slate/lib/changes/with-schema.js:106:5)
      at normalizeNodeAndChildren (node_modules/slate/lib/changes/with-schema.js:87:5)
      at Object.<anonymous>.Changes.normalizeNodeByKey (node_modules/slate/lib/changes/with-schema.js:53:3)
      at Change.call (node_modules/slate/lib/models/change.js:197:10)
      at Change.(anonymous function) [as normalizeNodeByKey] (node_modules/slate/lib/models/change.js:262:15)
      at Object.<anonymous>.Changes.normalizeDocument (node_modules/slate/lib/changes/with-schema.js:36:10)
      at Change.call (node_modules/slate/lib/models/change.js:197:10)
      at Change.(anonymous function) [as normalizeDocument] (node_modules/slate/lib/models/change.js:262:15)
      at Object.<anonymous>.Changes.normalize (node_modules/slate/lib/changes/with-schema.js:23:10)
      at Change.call (node_modules/slate/lib/models/change.js:197:10)
      at Change.(anonymous function) [as normalize] (node_modules/slate/lib/models/change.js:262:15)
      at Object.<anonymous>.exports.isEqual (src/test/_helpers/slateHyperscript.ts:48:5)

```

**Comment by CameronAckermanSEL** [comment]
That error is: https://github.com/ianstormtaylor/slate/pull/1538

**Comment by ch1ll0ut1** [comment]
@CameronAckermanSEL did u look at the last batch of comments from me?
one of them has the following code snippet handling the "child_type_invalid" case,
this is exactly the case which triggers the infinity loop
```javascript
'numbered-list': {
          nodes: [{ types: ['numbered-list-item'], min: 1 }],
          normalize: (change: Change, reason: string, context: NormalizeContext) => {
            switch (reason) {
              case 'child_type_invalid': {
                const { child, node } = context;

                if (child) {
                  return change.unwrapBlockByKey(node.key, 'numbered-list-item');
                }
              }
            }
            return;
          },
        },
```

**Comment by ch1ll0ut1** [comment]
@CameronAckermanSEL actually the funny thing is, I'm using his fork right now and got the above error^^

**Comment by CameronAckermanSEL** [comment]
Sorry, I should ask my question more directly. Does removing the `min: 1` constraint solve the problem?

**Comment by ch1ll0ut1** [comment]
removing min:1 =>
```javascript
return change.unwrapNodeByKey(node.key);  // Cannot read property 'nodes' of null
return change.unwrapNodeByKey(node.key, { normalize: false }); // Cannot read property 'nodes' of null
return change.unwrapBlockByKey(node.key, type + '-item'); // infinity loop
```

**Comment by ch1ll0ut1** [comment]
My overall idea for nested blocks is: all interaction only happens with the child, so for example the format buttons will only toggle list-item, but will not need to care about the parent block, or parent blocks from other blocks (like unwrapping numbered-list when switching to bulleted-list). To enable this concept i wrote the schema to automaticaly add or remove the parent (numbered-list / bulleted-list). 

1. if numbered-list-item is missing the numbered-list parent, i have to add the parent
2. if numbered-list has no numbered-list-item, then remove numbered-list

This allows me to have many plugins with nested blocks and i do not have to write logic to switch between all of them.

Schema for above rules
1)
```javascript
const type = 'numbered-list';

        [type + '-item']: {
          nodes: [{ objects: ['text'] }],
          parent: { types: [type] },
          normalize: (change: Change, reason: string, context: NormalizeContext) => {
            switch (reason) {
              case 'parent_type_invalid': {
                return change.wrapBlock(type);
              }
            }
            return;
          },
        },
```

2)
```javascript
const type = 'numbered-list';


        [type]: {
          nodes: [{ types: [type + '-item'], min: 1 }],
          normalize: (change, reason, context) => {
            switch (reason) {
              case 'child_type_invalid': {
                const { node } = context;
                  return change.unwrapNodeByKey(node.key);
              }
            }
            return;
          },
        },
```

**Comment by ch1ll0ut1** [comment]
uhh this one works, thanks @CameronAckermanSEL 

return change.unwrapBlockByKey(node.key, 'numbered-list');

**Comment by CameronAckermanSEL** [comment]
You are welcome! (this bug has a bounty on it but I will decline, I don't think its worth the posted amount :))

Glad you are up and running. Sorry for the time it took.

**Comment by Slapbox** [comment]
@CameronAckermanSEL out of curiosity, where is/was there a bounty on this bug?
