### ISSUE TITLE
Benchmark cannot be run

### ISSUE THREAD

**Issue by zhujinxuan** [ianstormtaylor/slate#1606]
#### Do you want to request a *feature* or report a *bug*?

bug

#### What's the current behavior?

In running benchmark and benchmark:save, it throws an error `import: undefined token`
This can be fixed by `BABEL_ENV=test babel-node .....`

However, there is another problem I do not know how to fix:
In running benchmark, it throws an error: 
```
module.js:491
    throw err;
    ^

Error: Cannot find module 'lodash.throttle'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jinxuanzhu/Slate/slate/packages/slate-react/lib/components/content.js:33:15)
    at Module._compile (module.js:573:30)
    at loader (/Users/jinxuanzhu/.nvm/versions/node/v8.4.0/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jinxuanzhu/.nvm/versions/node/v8.4.0/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
error Command failed with exit code 1.
```

**Comment by schneidmaster** [comment]
The first issue was probably caused by my rollup PR. The solution is as you suggest (add `cross-env BABEL_ENV=test` to the package.json script so babel transpiles the modules). Feel free to send a PR for that, or I can fix it tonight.

The second issue sounds like you need to run `yarn build` again -- your built version of `slate-react` in the `lib/` is still using `lodash.throttle`, whereas the source now uses `lodash/throttle` instead.

**Comment by zhujinxuan** [comment]
Thanks a lot~ . I will send a PR this afternoon
