### ISSUE TITLE
"$ yarn benchmark" is broken since 0.32.3 release

### ISSUE THREAD

**Issue by czechdave** [ianstormtaylor/slate#1660]
#### Do you want to request a _feature_ or report a _bug_?
bug

#### What's the current behavior?
`$ yarn benchmark`
throws:
```
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: spawn babel-node ENOENT
    at _errnoException (util.js:1003:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at process._tickCallback (internal/process/next_tick.js:152:19)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
```

#### What's the expected behavior?
`$ yarn benchmark` works

This error is introduced in the `0.32.3` release, `0.32.2` works without errors.

**Comment by czechdave** [comment]
Seems to be fixed by running:
`$ npm install -g babel-cli`

**Comment by SamyPesse** [comment]
I'm reopening this issue. It should be fixed by adding `babel-cli` as a dependency.
