### ISSUE TITLE
Moving cursor into an empty leaf results in slate crashing

### ISSUE THREAD

**Issue by gnalck** [ianstormtaylor/slate#1696]
#### Do you want to request a _feature_ or report a _bug_?
A bug

#### What's the current behavior?
moving cursor into an empty leaf can result in Slate crashing

fiddle: https://jsfiddle.net/hny81Ldp/ (place cursor at end, move to left with arrow key)
gif: https://media.giphy.com/media/xjWbZ8hrhqJetNhqGi/source.mp4
environment: Latest slate (whatever is on slatejs.org), on Chrome 64, Mac High Sierra

stack trace:
```
Error: Failed to execute 'setStart' on 'Range': The offset 4294967295 is larger than the node's length (1).
    at Ia (http://slatejs.org/main-5e3e645119bb7083cc71.js:1:138711)
    at a.t.updateSelection (http://slatejs.org/main-5e3e645119bb7083cc71.js:1:142929)
    at a.t.componentDidUpdate (http://slatejs.org/main-5e3e645119bb7083cc71.js:1:142562)
    at commitLifeCycles (http://slatejs.org/main-5e3e645119bb7083cc71.js:1:533249)
    at W (http://slatejs.org/main-5e3e645119bb7083cc71.js:1:539962)
    at HTMLUnknownElement.e (http://slatejs.org/main-5e3e645119bb7083cc71.js:1:422763)
    at Object.Oe (http://slatejs.org/main-5e3e645119bb7083cc71.js:1:422844)
    at invokeGuardedCallback (http://slatejs.org/main-5e3e645119bb7083cc71.js:1:421440)
    at U (http://slatejs.org/main-5e3e645119bb7083cc71.js:1:540725)
    at ee (http://slatejs.org/main-5e3e645119bb7083cc71.js:1:542675)

    in a (created by a)
    in a (created by a)
    in div (created by a)
    in div (created by a)
    in a (created by a)
    in a (created by a)
    in a (created by a)
    in div (created by a)
    in div (created by a)
    in a (created by a)
    in a (created by a)
    in a
    in a
```

#### What's the expected behavior?
To not crash! :)

**Comment by gnalck** [comment]
per discussion in slack, seems to be related to https://github.com/ianstormtaylor/slate/issues/1275

**Comment by ianstormtaylor** [comment]
I'm not able to reproduce this on the latest version of Slate, so this maybe be fixed. If not feel free to open again with more information, cheers.
