### ISSUE TITLE
track dirty nodes without using immutable maps

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#2196]
#### Do you want to request a _feature_ or report a _bug_?

Idea.

#### What's the current behavior?

Right now to keep track of dirty nodes, and to be able to process them in non-duplicate, depth-first order, we use an `Immutable.Map` with the `setIn` method. 

https://github.com/ianstormtaylor/slate/blob/ca6920a88f4e11f32c92e12106313c482ec45843/packages/slate/src/models/change.js#L180-L223

This makes it easy to build a non-duplicated tree and then iterate through it. But there is probably a smarter, faster way to use the list of paths directly instead of having to build and iterate the interim map data structure.

#### What's the expected behavior?

Same behavior, but anything that's faster than building and iterating the map.

**Comment by isubasti** [comment]
@ianstormtaylor depth first doesn't seems to be the right order here. I've run into a problem just now due to the depth first order approach. Let's modify the test code from https://github.com/ianstormtaylor/slate/blob/master/packages/slate/test/schema/custom/first-child-kind-invalid-default.js to

```js
/** @jsx h */

import h from '../../helpers/h'

export const schema = {
  blocks: {
    paragraph: {},
    quote: {
      nodes: [
        {
          match: [{ type: 'paragraph' }],
        },
      ],
    },
  },
}

export const input = (
  <value>
    <document>
      <quote>
        <image />
      </quote>
      <quote>
        <image />
      </quote>
    </document>
  </value>
)

export const output = (
  <value>
    <document />
  </value>
)
```

I would expect that to run properly but the second `quote` element could not be normalized properly as the path has changed by then. Here is the error that I got:
```
 1) slate schema custom child-type-invalid-default:
     Error: `Node.assertNode` could not find node with path or key: 1,0,0
      at Document.ElementInterface.(anonymous function) [as assertNode] (packages/slate/src/interfaces/element.js:1759:13)
      at Change.normalizePath (packages/slate/src/models/change.js:236:25)
      at Change.normalizeMapAndPath (packages/slate/src/models/change.js:221:10)
      at packages/slate/src/models/change.js:218:12
      at node_modules/immutable/dist/immutable.js:1379:16
      at ArrayMapNode.iterate.HashCollisionNode.iterate [as iterate] (node_modules/immutable/dist/immutable.js:1728:11)
      at Map.__iterate (node_modules/immutable/dist/immutable.js:1377:32)
      at Map.forEach (node_modules/immutable/dist/immutable.js:4383:19)
      at Change.normalizeMapAndPath (packages/slate/src/models/change.js:216:9)
      at packages/slate/src/models/change.js:218:12
      at node_modules/immutable/dist/immutable.js:1379:16
      at ArrayMapNode.iterate.HashCollisionNode.iterate [as iterate] (node_modules/immutable/dist/immutable.js:1728:11)
      at Map.__iterate (node_modules/immutable/dist/immutable.js:1377:32)
      at Map.forEach (node_modules/immutable/dist/immutable.js:4383:19)
      at Change.normalizeMapAndPath (packages/slate/src/models/change.js:216:9)
      at packages/slate/src/models/change.js:218:12
      at node_modules/immutable/dist/immutable.js:1379:16
      at ArrayMapNode.iterate.HashCollisionNode.iterate [as iterate] (node_modules/immutable/dist/immutable.js:1728:11)
      at Map.__iterate (node_modules/immutable/dist/immutable.js:1377:32)
      at Map.forEach (node_modules/immutable/dist/immutable.js:4383:19)
      at Change.normalizeMapAndPath (packages/slate/src/models/change.js:216:9)
      at packages/slate/src/models/change.js:200:12
      at Change.withoutNormalizing (packages/slate/src/models/change.js:302:5)
      at Change.normalizeKeys (packages/slate/src/models/change.js:199:10)
      at Change.normalize (packages/slate/src/models/change.js:154:10)
      at packages/slate/test/index.js:91:8
      at Context.<anonymous> (packages/slate-dev-test-utils/src/index.js:50:11)

```

**Comment by ianstormtaylor** [comment]
This is fixed now.
