### ISSUE TITLE
Using chrome plugin spell checker, editor throws error on misspelled word selection

### ISSUE THREAD

**Issue by asafron** [ianstormtaylor/slate#2620]
#### Do you want to request a _feature_ or report a _bug_?
bug

#### What's the current behavior?
I installed an external spell checker for chrome ([GINGER for chrome](https://chrome.google.com/webstore/detail/grammar-and-spelling-chec/kdfieneakcjfaiglcfcgkidlkmlijjnh?hl=en)). Using the "rich-text" demo (https://www.slatejs.org/#/rich-text) => Writing a few words with spelling mistake (so those word will get the red background) => Try selecting one of those words => Throws the following error:

Error: Failed to execute 'setStart' on 'Range': There is no child at offset 2.
    at ea (https://www.slatejs.org/main-e8e0520e642ae32de49e.js:1:179088)
    at a.n.updateSelection (https://www.slatejs.org/main-e8e0520e642ae32de49e.js:1:181441)
    at a.value (https://www.slatejs.org/main-e8e0520e642ae32de49e.js:1:183379)
    at Yo (https://www.slatejs.org/main-e8e0520e642ae32de49e.js:22:84563)
    at Zo (https://www.slatejs.org/main-e8e0520e642ae32de49e.js:22:81001)
    at Vo (https://www.slatejs.org/main-e8e0520e642ae32de49e.js:22:80500)
    at Wo (https://www.slatejs.org/main-e8e0520e642ae32de49e.js:22:80326)
    at Go (https://www.slatejs.org/main-e8e0520e642ae32de49e.js:22:79699)
    at yo (https://www.slatejs.org/main-e8e0520e642ae32de49e.js:22:78931)
    at Object.enqueueSetState (https://www.slatejs.org/main-e8e0520e642ae32de49e.js:22:54467)

GIF:
![slate-js-spell-checker](https://user-images.githubusercontent.com/1662857/53483606-7edfba00-3a8a-11e9-8eeb-931afac1b1cb.gif)

OS: Mac 10.14.3
Browser: Chrome 72.0.3626.119
Slate: Version used in demo site

#### What's the expected behavior?
Set the selection on the node that wrapped the spell checker node.

**Comment by ianstormtaylor** [comment]
Fixed by https://github.com/ianstormtaylor/slate/pull/3093.
