### ISSUE TITLE
Unexpected crashes/behavior when dealing with "contenteditable=false" divs

### ISSUE THREAD

**Issue by edmundluong88** [ianstormtaylor/slate#2751]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

OS: Ubuntu 18.04
Browser: Chrome Version 74.0.3729.131 (Official Build) (64-bit)
Slate: 0.44.12
Slate React: 0.21.18

I am trying to add a side panel to my Editor that will be attached to every Block node that represents a line of text. In this side panel, there will be tools (such as to assign a User to the line, etc). Currently I am trying to implement an Input/Dropdown using [react-select](https://github.com/JedWatson/react-select) in this side panel so that Users can type in or select a name, however, I am running into some bugs with both implementation methods I have tried.

Referencing the [Slate FAQ](https://docs.slatejs.org/general/faq#what-can-a-block-node-have-as-its-children):

> If you have an element that is not going to be editable, you can choose between a void node or just a DOM element with contentEditable = {false}. Opt for the void node if you would like it represented in the Slate schema, and for Slate to be aware of it.

I initially opt-ed for going the `contentEditable=false` method, and added that attribute to the div that contains my side panel. This works well for allowing me to type into the input (without that attribute, I was not able to type into it). 

However, as shown below, I can consistently crash the application by clicking on some text in my Editor, and then select an option from my dropdown in my side panel. Strangely, without selecting any text in my editor, I can freely select options from the dropdown and type in my input. Once I select ANY text in the editor and then the buggy behavior occurs:

![out3](https://user-images.githubusercontent.com/29665373/57478294-8e3c6a00-7268-11e9-9d86-312b65360ca5.gif)

Here is the stack trace of the error that occurs:

```
slate-react.js?b54d:4651 Uncaught DOMException: Failed to execute 'getRangeAt' on 'Selection': 0 is not a valid index.
    at Content._this.updateSelection (webpack-internal:///./node_modules/slate-react/lib/slate-react.js:4651:46)
    at Content.componentDidUpdate (webpack-internal:///./node_modules/slate-react/lib/slate-react.js:4847:12)
    at commitLifeCycles (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:17314:22)
    at commitAllLifeCycles (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:18701:7)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:149:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:199:16)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:256:31)
    at commitRoot (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:18913:7)
    at eval (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20383:5)
    at Object.unstable_runWithPriority (webpack-internal:///./node_modules/react-dom/node_modules/scheduler/cjs/scheduler.development.js:255:12)
Content._this.updateSelection @ slate-react.js?b54d:4651
componentDidUpdate @ slate-react.js?b54d:4847
commitLifeCycles @ react-dom.development.js?61bb:17314
commitAllLifeCycles @ react-dom.development.js?61bb:18701
callCallback @ react-dom.development.js?61bb:149
invokeGuardedCallbackDev @ react-dom.development.js?61bb:199
invokeGuardedCallback @ react-dom.development.js?61bb:256
commitRoot @ react-dom.development.js?61bb:18913
(anonymous) @ react-dom.development.js?61bb:20383
unstable_runWithPriority @ scheduler.development.js?1911:255
completeRoot @ react-dom.development.js?61bb:20382
performWorkOnRoot @ react-dom.development.js?61bb:20311
performWork @ react-dom.development.js?61bb:20219
performSyncWork @ react-dom.development.js?61bb:20193
requestWork @ react-dom.development.js?61bb:20062
scheduleWork @ react-dom.development.js?61bb:19876
enqueueSetState @ react-dom.development.js?61bb:11155
Component.setState @ react.development.js?72d0:335
handleOnChange @ TranscriptionEditor.js?cf6e:40
handleChange @ slate-react.js?b54d:5367
onChange @ slate-react.js?b54d:5234
flush @ slate.js?4d4d:11125
(anonymous) @ slate.js?4d4d:11101
Promise.then (async)
applyOperation @ slate.js?4d4d:11100
applyOperation @ slate-react.js?b54d:5380
Commands$5.setData @ slate.js?4d4d:9517
command @ slate.js?4d4d:11148
command @ slate-react.js?b54d:5387
onCommand @ slate.js?4d4d:5821
next @ slate.js?4d4d:11315
run @ slate.js?4d4d:11349
command @ slate.js?4d4d:11155
method @ slate.js?4d4d:11242
(anonymous) @ slate.js?4d4d:8393
Commands$3.withoutSaving @ slate.js?4d4d:8505
command @ slate.js?4d4d:11148
command @ slate-react.js?b54d:5387
onCommand @ slate.js?4d4d:5821
next @ slate.js?4d4d:11315
run @ slate.js?4d4d:11349
command @ slate.js?4d4d:11155
method @ slate.js?4d4d:11242
Commands$3.save @ slate.js?4d4d:8390
command @ slate.js?4d4d:11148
command @ slate-react.js?b54d:5387
onCommand @ slate.js?4d4d:5821
next @ slate.js?4d4d:11315
run @ slate.js?4d4d:11349
command @ slate.js?4d4d:11155
method @ slate.js?4d4d:11242
(anonymous) @ slate.js?4d4d:11077
withoutNormalizing @ slate.js?4d4d:11405
applyOperation @ slate.js?4d4d:11076
applyOperation @ slate-react.js?b54d:5380
Commands$2.setNodeByPath @ slate.js?4d4d:7992
command @ slate.js?4d4d:11148
command @ slate-react.js?b54d:5387
onCommand @ slate.js?4d4d:5821
next @ slate.js?4d4d:11315
run @ slate.js?4d4d:11349
command @ slate.js?4d4d:11155
method @ slate.js?4d4d:11242
Commands$2.<computed> @ slate.js?4d4d:8276
command @ slate.js?4d4d:11148
command @ slate-react.js?b54d:5387
onCommand @ slate.js?4d4d:5821
next @ slate.js?4d4d:11315
run @ slate.js?4d4d:11349
command @ slate.js?4d4d:11155
method @ slate.js?4d4d:11242
_setLineSpeaker @ TranscriptionEditor.js?cf6e:346
setLineSpeaker @ TranscriptionEditor.js?cf6e:362
handleOnChange @ SpeakersInput.js?4b6b:24
callProp @ stateManager.js?a145:138
(anonymous) @ stateManager.js?a145:75
(anonymous) @ Creatable.js?e836:137
(anonymous) @ Select.js?8cc6:216
(anonymous) @ Select.js?8cc6:241
(anonymous) @ Select.js?8cc6:290
onSelect @ Select.js?8cc6:1358
callCallback @ react-dom.development.js?61bb:149
invokeGuardedCallbackDev @ react-dom.development.js?61bb:199
invokeGuardedCallback @ react-dom.development.js?61bb:256
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js?61bb:270
executeDispatch @ react-dom.development.js?61bb:561
executeDispatchesInOrder @ react-dom.development.js?61bb:580
executeDispatchesAndRelease @ react-dom.development.js?61bb:680
executeDispatchesAndReleaseTopLevel @ react-dom.development.js?61bb:688
forEachAccumulated @ react-dom.development.js?61bb:662
runEventsInBatch @ react-dom.development.js?61bb:816
runExtractedEventsInBatch @ react-dom.development.js?61bb:824
handleTopLevel @ react-dom.development.js?61bb:4826
batchedUpdates$1 @ react-dom.development.js?61bb:20404
batchedUpdates @ react-dom.development.js?61bb:2151
dispatchEvent @ react-dom.development.js?61bb:4905
(anonymous) @ react-dom.development.js?61bb:20455
unstable_runWithPriority @ scheduler.development.js?1911:255
interactiveUpdates$1 @ react-dom.development.js?61bb:20454
interactiveUpdates @ react-dom.development.js?61bb:2170
dispatchInteractiveEvent @ react-dom.development.js?61bb:4882
Show 70 more frames
```

This issue seems related to this current open issue: https://github.com/ianstormtaylor/slate/issues/1237

I placed a breakpoint down on the line where its crashing and here is what is in the local scope:

![slate2](https://user-images.githubusercontent.com/29665373/57479364-3c491380-726b-11e9-826e-a02c1be06572.png)

It appears Slate sees that I have actually selected my react-select input and wants to handle it. It is calling `getRangeAt(0)` on `native`, but looking into the `native` variable, the `rangeCount` is 0.

#### What's the expected behavior?

Ideally, the selection of the dropdown option in the select box should not trigger anything on Slate. As of right now, it looks like selecting something in that select box triggers the `updateSelection` call within Slate, causing an error.

Please let me know if any more information is required. Thanks for the great work!

**Comment by steida** [comment]
Use `user-select: none;`, Luke ✨

**Comment by edmundluong88** [comment]
@steida that worked perfectly! Amazing what one line of code can do for you...... Thank you very much!

**Comment by steida** [comment]
@edmundluong88 Give https://github.com/este/este star pls ;)
