### ISSUE TITLE
Cannot run examples anymore

### ISSUE THREAD

**Issue by ajpalkovic** [ianstormtaylor/slate#3121]
Commit dd6438436df1191d20f91177ed720f119550d448 breaks `yarn start`.  Reverting it fixes the examples.  The error it produces is:
```
$ yarn start
yarn run v1.19.1
$ npm-run-all --parallel --print-label watch server
[watch ] $ rollup --config ./support/rollup/config.js --watch
[server] $ webpack-dev-server --config ./support/webpack/config.js
[watch ] rollup v0.55.1
[watch ] bundles packages/slate/src/index.js → packages/slate/lib/slate.es.js, packages/slate/lib/slate.js...
[server] internal/modules/cjs/loader.js:783
[server]     throw err;
[server]     ^
[server]
[server] Error: Cannot find module 'webpack-cli/bin/config-yargs'
[server] Require stack:
[server] - xxxx/node_modules/webpack-dev-server/bin/webpack-dev-server.js
[server]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
[server]     at Function.Module._load (internal/modules/cjs/loader.js:685:27)
[server]     at Module.require (internal/modules/cjs/loader.js:838:19)
[server]     at require (internal/modules/cjs/helpers.js:74:18)
[server]     at Object.<anonymous> (xxxx/node_modules/webpack-dev-server/bin/webpack-dev-server.js:84:1)
[server]     at Module._compile (internal/modules/cjs/loader.js:945:30)
[server]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
[server]     at Module.load (internal/modules/cjs/loader.js:798:32)
[server]     at Function.Module._load (internal/modules/cjs/loader.js:711:12)
[server]     at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10) {
[server]   code: 'MODULE_NOT_FOUND',
[server]   requireStack: [
[server]     'xxxx/node_modules/webpack-dev-server/bin/webpack-dev-server.js'
[server]   ]
[server] }
[server] error Command failed with exit code 1.
[server] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[watch ] error Command failed with signal "SIGTERM".
[watch ] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "server" exited with 1.
error Command failed with exit code 1.
```

This issue talks about the bug: https://github.com/webpack/webpack-dev-server/issues/2029
I tried upgrading webpack-dev-server to latest, but I think that's also incompatible with the version of webpack you're on?

**Comment by ianstormtaylor** [comment]
Fixed by https://github.com/ianstormtaylor/slate/pull/3093.
