### ISSUE TITLE
yarn test throw TypeError: children.filter(...).flat is not a function

### ISSUE THREAD

**Issue by Jokcy** [ianstormtaylor/slate#3203]
#### Do you want to request a _feature_ or report a _bug_?

maybe a bug

#### What's the current behavior?

Follow setup doc setup my local repo
https://docs.slatejs.org/general/contributing#repository-setup

Then I try to run `yarn test`, about 80% tests just throw error, and all error info is the same:
```
618) slate
       transforms
         splitNodes
           point
             block-void :
     TypeError: children.filter(...).flat is not a function
      at jsx (../src/hyperscript.ts:99:5)
      at Object.<anonymous> (packages/slate/test/transforms/splitNodes/point/block-void.js:12:5)
      at Module._compile (internal/modules/cjs/loader.js:688:30)
      at Module._compile (node_modules/pirates/lib/index.js:99:24)
      at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
      at Object.newLoader [as .js] (node_modules/pirates/lib/index.js:104:7)
      at Module.load (internal/modules/cjs/loader.js:598:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
      at Function.Module._load (internal/modules/cjs/loader.js:529:3)
      at Module.require (internal/modules/cjs/loader.js:636:17)
      at require (internal/modules/cjs/helpers.js:20:18)
      at Context.<anonymous> (support/fixtures.js:39:26)
```

![image](https://user-images.githubusercontent.com/2088642/70031285-da287500-15e5-11ea-83ac-f6d06d9a717a.png)

Slate: 0.50
OS: Mac

#### What's the expected behavior?

run tests success

**Comment by Jokcy** [comment]
em...... it seems my node version(10.13.0) not support `flat` , is it better to transform it?
