### ISSUE TITLE
Undo of a paste is not working

### ISSUE THREAD

**Issue by SamyPesse** [ianstormtaylor/slate#352]
In the rich text example, copy some text and paste it in the same example; then press "cmd-Z", it will throw an error:

```
Uncaught Error: Could not find a descendant at path "1,1".
    at Document.assertPath (http://slatejs.org/build.prod.js:8609:13)
    at removeNode (http://slatejs.org/build.prod.js:14604:23)
    at Object.applyOperation (http://slatejs.org/build.prod.js:14442:21)
    at Transform.(anonymous function) [as applyOperation] (http://slatejs.org/build.prod.js:12267:39)
    at http://slatejs.org/build.prod.js:16999:17
    at Array.forEach (native)
    at http://slatejs.org/build.prod.js:16998:16
    at Array.forEach (native)
    at Object.undo (http://slatejs.org/build.prod.js:16997:30)
    at Transform.(anonymous function) [as undo] (http://slatejs.org/build.prod.js:12267:39)
```

**Comment by tyler-johnson** [comment]
I am getting something similar when I delete multiple block nodes and try to undo. I am seeing an almost identical error: `Uncaught Error: Could not find a descendant at path "0,1".`

**Comment by ianstormtaylor** [comment]
I can't reproduce this one anymore in the latest builds, so I'm going to close. If you see this happening still let me know!

**Comment by nimamehanian** [comment]
I'm getting it too. I'm on 0.19.21. I can't make sense of the trace.
However, it consistently happens if, with nested list items, I make two children in a parent, and attempt to hit backspace at the beginning of the line of the first child (in an attempt to move its text up onto the parent's).
