### ISSUE TITLE
Paste fails when at top of document

### ISSUE THREAD

**Issue by atombender** [ianstormtaylor/slate#425]
Based on [the public demo](http://slatejs.org/#/rich-text?_k=uqglmg), reproduce with these steps:

1. Copy all the text (cmd-A, cmd-C).
2. Put cursor at beginning of document.
3. Paste (cmd-V). Will fail with `TypeError: Cannot read property 'marks' of undefined`:

```
TypeError: Cannot read property 'marks' of undefined
    at Document.getMarksAtRange (http://slatejs.org/build.prod.js:9493:19)
    at Document.object.(anonymous function) [as getMarksAtRange] (http://slatejs.org/build.prod.js:18722:30)
    at State.get (http://slatejs.org/build.prod.js:11980:100)
    at RichText._this.hasMark (http://slatejs.org/build.prod.js:4151:19)
    at RichText._this.renderMarkButton (http://slatejs.org/build.prod.js:4258:28)
    at RichText._this.renderToolbar (http://slatejs.org/build.prod.js:4247:15)
    at RichText._this.render (http://slatejs.org/build.prod.js:4240:15)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (http://slatejs.org/build.prod.js:69470:32)
    at ReactCompositeComponentWrapper._renderValidatedComponent (http://slatejs.org/build.prod.js:69493:34)
    at ReactCompositeComponentWrapper._updateRenderedComponent (http://slatejs.org/build.prod.js:69417:36)
```

**Comment by ianstormtaylor** [comment]
Thanks so much for reporting this @atombender! I've just pushed up a fix, and it will be in the `0.15.8` which I'm releasing now.
