### ISSUE TITLE
Undo(cmd-z) fails when there are Marks in Block.

### ISSUE THREAD

**Issue by websymphony** [ianstormtaylor/slate#426]
Steps to reproduce on example website: http://slatejs.org/#/auto-markdown

**Scenario A:**
1. Cmd-a (Select all text)
2. Delete selected text.
3. Cmd-z (Try to undo)

**Scenario B - after reloading the same page:**
1. Select partial text from Blockquote and partial text from paragraph below.
2. Delete selected text.
3. Cmd-z (Try to undo)

Error:
```
Uncaught Error: Could not find a descendant at path "0,1".
    at Document.assertPath (http://slatejs.org/build.prod.js:8877:13)
    at moveNode (http://slatejs.org/build.prod.js:15068:25)
    at Object.applyOperation (http://slatejs.org/build.prod.js:14959:23)
    at Transform.(anonymous function) [as applyOperation] (http://slatejs.org/build.prod.js:12672:39)
    at http://slatejs.org/build.prod.js:17581:17
    at Array.forEach (native)
    at http://slatejs.org/build.prod.js:17580:16
    at Array.forEach (native)
    at Object.undo (http://slatejs.org/build.prod.js:17579:30)
    at Transform.(anonymous function) [as undo] (http://slatejs.org/build.prod.js:12672:39)
```

This does not happen when there are no Marks in the Block, for eg here: http://slatejs.org/#/plain-text.

**Comment by ianstormtaylor** [comment]
I believe this is fixed in `0.15`! If you run into it again feel free to re-open though.
