### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getRanges' / 'nodeType' of undefined

### ISSUE THREAD

**Issue by bkniffler** [ianstormtaylor/slate#493]
Hi, 
Is no one else stumbling across these two?
- Cannot read property 'getRanges' of undefined
- Cannot read property 'nodeType' of undefined

I'm seeing those regularly. I've not been able to reproduce them in an isolated environment yet, but I suppose its got something to do with custom blocks. I'm going to try and find out more, but I hoped that someone else might already have seen it? Or maybe you already got an idea @ianstormtaylor?

Gifs:
![dez -02-2016 20-38-15](https://cloud.githubusercontent.com/assets/4349324/20849595/5cbd4d00-b8cf-11e6-94fc-21dc81dd27fd.gif)
![dez -02-2016 20-38-33](https://cloud.githubusercontent.com/assets/4349324/20849594/5cbbc17e-b8cf-11e6-907e-f3cace5ad750.gif)

Stacktraces:
```
Uncaught TypeError: Cannot read property 'getRanges' of undefined
    at Content.getPoint (http://localhost:3011/client/index.js:189565:24)
    at onSelect (http://localhost:3011/client/index.js:190136:29)
    at Object.ReactErrorUtils.invokeGuardedCallback (http://localhost:3011/client/index.js:59128:16)
    at executeDispatch (http://localhost:3011/client/index.js:58657:21)
    at Object.executeDispatchesInOrder (http://localhost:3011/client/index.js:58680:5)
    at executeDispatchesAndRelease (http://localhost:3011/client/index.js:38239:22)
    at executeDispatchesAndReleaseTopLevel (http://localhost:3011/client/index.js:38250:10)
    at Array.forEach (native)
    at forEachAccumulated (http://localhost:3011/client/index.js:95025:9)
    at Object.processEventQueue (http://localhost:3011/client/index.js:38453:7)
getPoint @ content.js:157
onSelect @ content.js:728
ReactErrorUtils.invokeGuardedCallback @ ReactErrorUtils.js:70
executeDispatch @ EventPluginUtils.js:85
executeDispatchesInOrder @ EventPluginUtils.js:108
executeDispatchesAndRelease @ EventPluginHub.js:43
executeDispatchesAndReleaseTopLevel @ EventPluginHub.js:54
forEachAccumulated @ forEachAccumulated.js:24
processEventQueue @ EventPluginHub.js:257
runEventQueueInBatch @ ReactEventEmitterMixin.js:17
handleTopLevel @ ReactEventEmitterMixin.js:28
handleTopLevelImpl @ ReactEventListener.js:72
perform @ Transaction.js:140
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
batchedUpdates @ ReactUpdates.js:97
dispatchEvent @ ReactEventListener.js:147
index.js:239 [] [Object, Object]
```

```
normalize-node-and-offset.js:57 Uncaught TypeError: Cannot read property 'nodeType' of undefined
    at getNonComment (http://localhost:3011/client/index.js:197519:15)
    at normalizeNodeAndOffset (http://localhost:3011/client/index.js:197485:12)
    at Object.findKey (http://localhost:3011/client/index.js:65459:68)
    at Content.getPoint (http://localhost:3011/client/index.js:189560:43)
    at onSelect (http://localhost:3011/client/index.js:190136:29)
    at Object.ReactErrorUtils.invokeGuardedCallback (http://localhost:3011/client/index.js:59128:16)
    at executeDispatch (http://localhost:3011/client/index.js:58657:21)
    at Object.executeDispatchesInOrder (http://localhost:3011/client/index.js:58680:5)
    at executeDispatchesAndRelease (http://localhost:3011/client/index.js:38239:22)
    at executeDispatchesAndReleaseTopLevel (http://localhost:3011/client/index.js:38250:10)
getNonComment @ normalize-node-and-offset.js:57
normalizeNodeAndOffset @ normalize-node-and-offset.js:23
findKey @ offset-key.js:68
getPoint @ content.js:152
onSelect @ content.js:728
ReactErrorUtils.invokeGuardedCallback @ ReactErrorUtils.js:70
executeDispatch @ EventPluginUtils.js:85
executeDispatchesInOrder @ EventPluginUtils.js:108
executeDispatchesAndRelease @ EventPluginHub.js:43
executeDispatchesAndReleaseTopLevel @ EventPluginHub.js:54
forEachAccumulated @ forEachAccumulated.js:24
processEventQueue @ EventPluginHub.js:257
runEventQueueInBatch @ ReactEventEmitterMixin.js:17
handleTopLevel @ ReactEventEmitterMixin.js:28
handleTopLevelImpl @ ReactEventListener.js:72
perform @ Transaction.js:140
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
batchedUpdates @ ReactUpdates.js:97
dispatchEvent @ ReactEventListener.js:147
```

**Comment by ianstormtaylor** [comment]
Hey @bkniffler, I'm not sure exactly.

---

The `Cannot read property 'nodeType'` happens when Slate is trying to translate a DOM selection into its `Selection` model representation. But it seems like there's a case that it's not handling well. A few questions for that one:

- What does the DOM look like in the component that you're clicking into that throws the error?
- What is the native DOM selection `anchorNode, anchorOffset, focusNode, focusOffset`?

---

For the second one, I'm not totally sure either, but it seems like it would happen when Slate is trying to resolve the DOM selection, and finds an element with `data-offset-key` in the DOM, but with a `key` that doesn't actually map to a DOM node. Questions:

- Are you using the built-in key generator? or supplying your own?
- Before that error is thrown, are there any DOM nodes with `data-offset-key` with keys that no longer exist in the Slate document?

**Comment by ianstormtaylor** [comment]
For the first error, I've got an update: I've got a similar error being thrown in my own codebase now, so it might be for the same reason. 

I've just pushed up `0.16.1`, so see if that solves your issue!

**Comment by bkniffler** [comment]
Indeed, `Cannot read property 'nodeType'` is gone now, great work!

For the other one, I'll check now and see.

**Comment by bkniffler** [comment]
It seems like there is a data-offset-key in my DOM with a key that doesn't exist..
I'm using the build-in generator.

The block that causes the error if I click onto it is a normal `<div {...props.attributes}>` that has `isVoid: true`. Another block with `isVoid: false` doesn't throw an error if clicked.

```
<div style="position: relative;">
   <span style="position: absolute; top: 0px; left: -9999px; text-indent: -9999px;">
      <span data-offset-key="30-0">
         <span class="slate-zero-width-space">​</span>
      </span>
   </span>
   <div contenteditable="false">
      <div data-block-active="true" data-key="28">
         ...
      </div>
   </div>
</div>
```

Going to look further..

**Comment by bkniffler** [comment]
Ah, I missed an important thing which I just noticed (its a colleagues code). The custom block has `isVoid: true` and is nesting another component, that has a `<Slate readOnly={true} />` instance to show rich text. Just imagine it is a blog block to show posts inside of the main slate instance, and each post component has a `<Slate readOnly={true} />` to show an extract of the post. Does this make sense?

But isn't this something that should work?

**Comment by ianstormtaylor** [comment]
Interesting, yeah we definitely want to make that nested case work.

My guess is it's just an assumption I made about the DOM structure, not thinking that there might be nested read-only editor that wouldn't capture the inner events. Can you copy-paste the DOM structure of the component and the nested editor?

**Comment by bkniffler** [comment]
Yes sure

```html
<div class="frontend-editor" style="position: relative;">
  <div contenteditable="true" spellcheck="true" style="outline: none; white-space: pre-wrap; word-wrap: break-word; -webkit-user-modify: read-write-plaintext-only;">
    <div data-block-active="true" data-key="6">
      <div class="column_left">
        Left column
      </div>
      <div class="home">
        <div style="position: relative;">
          <span style="position: absolute; top: 0px; left: -9999px; text-indent: -9999px;"><span data-offset-key="12-0"><span class="slate-zero-width-space">​</span></span></span>
          <div contenteditable="false">
            <div data-block-active="false" data-key="1">
              <div class="ui relaxed divided list beitrag_list" style="margin: 0px;">
                <div style="clear: both;"></div>
              </div>
              <div class="ui relaxed divided list beitrag_list" style="margin: 0px;">
                <div class="beitrag">
                  <div class="header">
                    <h2>Topic</h2>
                  </div>
                  <div class="text">
                    <div class="date">
                      16.11.2016
                    </div>
                    <div style="position: relative;">
                      <!-- react-empty: 318 -->
                      <div contenteditable="false" spellcheck="true" style="outline: none; white-space: pre-wrap; word-wrap: break-word;">
                        <div data-key="1" style="position: relative;">
                          <span data-key="0"><span data-offset-key="0-0">Blablab bla</span></span>
                        </div>
                        <div data-key="3" style="position: relative;">
                          <span data-key="2"><span data-offset-key="2-0">Blabla.</span></span>
                        </div>
                        <div data-key="5" style="position: relative;">
                          <span data-key="4"><span data-offset-key="4-0"><br></span></span>
                        </div>
                        <div data-key="7" style="position: relative;">
                          <span data-key="6"><span data-offset-key="6-0">Blabla</span></span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div style="clear: both;"></div>
              </div>
            </div>
          </div>
        </div>
        <p data-key="3"><span data-key="2"><span data-offset-key="2-0"><br></span></span></p>
        <p data-key="5"><span data-key="4"><span data-offset-key="4-0"><br></span></span></p><!-- react-empty: 395 -->
      </div>
      <div class="column_right"></div>
    </div>
    <p data-key="8"><span data-key="7"><span data-offset-key="7-0"><br></span></span></p>
    <p data-key="10"><span data-key="9"><span data-offset-key="9-0"><br></span></span></p>
  </div>
</div>
```

**Comment by ianstormtaylor** [comment]
@bkniffler does this still fail in the latest version of Slate?

**Comment by bkniffler** [comment]
Unforunately not, I got the new `data-slate-editor` attribute in my DOM, but the error persists. As soon as I click the nested editor. The stack and message are the same :(

**Comment by ianstormtaylor** [comment]
Hey @bkniffler I just pushed up a new approach to handling selection normalizing for void nodes, so hopefully that will finally solve it! Let me know if it does.

**Comment by bkniffler** [comment]
heya! That did the trick @ianstormtaylor, great work!
