### ISSUE TITLE
Can't removeNodeById on block if it is the only block in editor

### ISSUE THREAD

**Issue by bkniffler** [ianstormtaylor/slate#504]
Hey,
Calling `removeNodeById` on a block if it is the only block in editor throws `Cannot read property 'key' of undefined.

Reproduce:
https://jsfiddle.net/2zokvrvt/29/

Stack-Trace
```
normalize.js:95 Uncaught TypeError: Cannot read property 'key' of undefined
    at Object.normalizeSelection (http://localhost:3011/client/index.js:201357:27)
    at Transform.(anonymous function) [as normalizeSelection] (http://localhost:3011/client/index.js:196901:32)
    at Transform.apply (http://localhost:3011/client/index.js:196851:17)
    at toggle (http://localhost:3011/client/0.b75dd7a02eab3f957e06.hot-update.js:195:58)
    at http://localhost:3011/client/0.b75dd7a02eab3f957e06.hot-update.js:117:13
    at Object.ReactErrorUtils.invokeGuardedCallback (http://localhost:3011/client/index.js:59029:16)
    at executeDispatch (http://localhost:3011/client/index.js:58558:21)
    at Object.executeDispatchesInOrder (http://localhost:3011/client/index.js:58581:5)
    at executeDispatchesAndRelease (http://localhost:3011/client/index.js:38431:22)
    at executeDispatchesAndReleaseTopLevel (http://localhost:3011/client/index.js:38442:10)
```

**Comment by ianstormtaylor** [comment]
Hey @bkniffler thanks for this! I'm going to merge this one into #505 since it seems like you both ran into the same issue at the same time in two PRs 😄
