### ISSUE TITLE
Chinese IME sogou，cause crash by editing text before a inline-element

### ISSUE THREAD

**Issue by OldDream** [ianstormtaylor/slate#5066]
**Description**
Chinese IME sogou，cause crash by editing text before a inline-element. 
select -> input by sogou IME -> crash

**Recording**
![rec](https://user-images.githubusercontent.com/18358438/181482462-8517f926-0f3a-4f81-9c21-034ded4fc692.gif)

**Sandbox**

This bug can be reproduce by official online demo.
https://www.slatejs.org/examples/mentions

**Steps**
To reproduce the behavior:
1. select all characters befor `@R2-D2`
2. start input with sogou IME
3. then the bug show up.
4. See error in console:
`Uncaught Error: Cannot resolve a Slate point from DOM point: [object Text],2
    at Object.toSlatePoint ([example]-5e4f16b701ecada0.js:1:99830)
    at Object.toSlateRange ([example]-5e4f16b701ecada0.js:1:100498)
    at HTMLDocument.<anonymous> ([example]-5e4f16b701ecada0.js:1:117948)
    at g (674-c731382ea76bd727.js:1:1377655)
    at b (674-c731382ea76bd727.js:1:1377711)
    at HTMLDocument.z (674-c731382ea76bd727.js:1:1378030)
    at g (674-c731382ea76bd727.js:1:1377655)
    at S (674-c731382ea76bd727.js:1:1377930)
    at w (674-c731382ea76bd727.js:1:1377820)`

**Context**
The official demo can work smooth with Microsoft's chinese IME, so I'm not sure if this is a bug. But sogou IME is widely used in china. It  would be very helpful if we can fix this.

**Comment by washanhanzi** [comment]
#5762

**Comment by laden666666** [comment]
Only specific versions of Sogou IME have this bug: 

When editing selected content, these versions of the IME do not delete the selected content immediately. Instead, they delete the content after the IME finishes processing (i.e., at the compositionend event).

When slate starts receiving input (at the compositionstart event), it will delete the selected content. However, when the Sogou IME detects that the selected content has been deleted, it reinserts the selected text. This creates a discrepancy between Slate's HTML DOM and Slate children, leading to crash.

I conducted tests on similar products such as Lexical, Tiptap, DraftJS, and QuillJS. All of them can reproduce the issue where the selected text is not deleted immediately, but none of them crash. Although it's not perfect, they can still complete text editing normally using Sogou IME.
