### ISSUE TITLE
Nesting editor instances

### ISSUE THREAD

**Issue by bkniffler** [ianstormtaylor/slate#578]
Hi, 
When trying to nest editors there is the following error as soon as you click somewhere.
```
Uncaught TypeError: Cannot read property 'getRanges' of undefined
    at Content.getPoint (https://npmcdn.com/slate@0.16.11/dist/slate.js:32068:24)
    at onSelect (https://npmcdn.com/slate@0.16.11/dist/slate.js:32641:29)
    at Object.ReactErrorUtils.invokeGuardedCallback (https://npmcdn.com/react-dom@15.4.2/dist/react-dom.js:9017:16)
    at executeDispatch (https://npmcdn.com/react-dom@15.4.2/dist/react-dom.js:3006:21)
    at Object.executeDispatchesInOrder (https://npmcdn.com/react-dom@15.4.2/dist/react-dom.js:3029:5)
    at executeDispatchesAndRelease (https://npmcdn.com/react-dom@15.4.2/dist/react-dom.js:2431:22)
    at executeDispatchesAndReleaseTopLevel (https://npmcdn.com/react-dom@15.4.2/dist/react-dom.js:2442:10)
    at Array.forEach (native)
    at forEachAccumulated (https://npmcdn.com/react-dom@15.4.2/dist/react-dom.js:15423:9)
    at Object.processEventQueue (https://npmcdn.com/react-dom@15.4.2/dist/react-dom.js:2645:7)
```

Here is an example:
https://jsfiddle.net/2zokvrvt/36/

Also, I've had problems with the node keys. Is it possible, in a more complex scenario, that nesting editors with different documents can cause issues with conflicting node keys, since the generator is static? I know its not an issue if you use different editors side-by-side, but in one-another?

**Comment by joetuson** [comment]
I encountered this issue yesterday.

Setting the parent Editor to `readOnly` when you focus the child Editor seemed to fix this for me.

**Comment by ianstormtaylor** [comment]
This issue hasn't had a response in a while, and it's unclear if it's still present in the latest versions of Slate. To keep the issues easier to manage, since there are so many being opened every day, I'm going to close this old one out. 

But if you notice that the bug is still happening, please feel free to comment and it can be revisited. It might be an edge case that not many people run into, in which case the fastest way to get it fixed would probably be to write a pull request for it.

Thanks for understanding!
