### ISSUE TITLE
Errors deleting links on the link example

### ISSUE THREAD

**Issue by oyeanuj** [ianstormtaylor/slate#630]
Hi @ianstormtaylor! On the [link example](http://slatejs.org/#/links?_k=lgujwr), in the following two cases, I see errors and unexpected behavior:

### First Case (steps)
1. Select-all text.
2. Press delete.
3. In the empty editor, type in a word.
4. Select, and click on link button.
5. Enter a url
6. Go to the end of the word and try to delete or highlight and try to delete.
7. Check console.

The following errors should show up:
```js
Uncaught TypeError: Cannot read property 'length' of undefined
    at Object.deleteBackwardAtRange (http://slatejs.org/build.prod.js:18329:32)
    at Transform.(anonymous function) [as deleteBackwardAtRange] (http://slatejs.org/build.prod.js:14125:32)
    at Object.deleteCharBackwardAtRange (http://slatejs.org/build.prod.js:18177:13)
    at Transform.(anonymous function) [as deleteCharBackwardAtRange] (http://slatejs.org/build.prod.js:14125:32)
    at Object.deleteCharBackward (http://slatejs.org/build.prod.js:17546:13)
    at Transform.(anonymous function) [as deleteCharBackward] (http://slatejs.org/build.prod.js:14125:32)
    at onKeyDownBackspace (http://slatejs.org/build.prod.js:14672:63)
    at Stack.(anonymous function) [as onKeyDown] (http://slatejs.org/build.prod.js:12580:37)
    at Object._this.(anonymous function) [as onKeyDown] (http://slatejs.org/build.prod.js:6505:70)
    at onKeyDown (http://slatejs.org/build.prod.js:6156:18)
```

### Second Case
1. Highlight the last word 'selected'.
2. Add a link.
3. Move the cursor to the right, past the period.
4. Now observe two issues
  1. Highlight from the end of the line including the period and the link and try to backspace. Random fragments are being deleted and selection still remains expanded.
  2. Now try the above steps but try backspacing without highlighting and you'll see that the period is not being deleted.

On the positive side, no console errors are showing up though.

**Comment by oyeanuj** [comment]
This also seems related to #611 and even possibly #627.

**Comment by oyeanuj** [comment]
I've also added some GIFs to the original comment for clarity.

**Comment by oyeanuj** [comment]
Just re-tested. The first issue seems to have been resolved in the subsequent releases. The other two can still be reproduced.

**Comment by vpontis** [comment]
Interesting, it looks like both are non-issues for me now _because_ when I add a link the selection is removed. So that looks like another bug.k

**Comment by oyeanuj** [comment]
It seems that out of the 3, the first 2 issues have been resolved in subsequent releases, yay! Only the third issue persists -
 
![image](https://user-images.githubusercontent.com/9633371/28884729-ef698de2-7767-11e7-839a-ba88ed195259.png)

1. Highlight the last word 'selected'.
2. Add a link.
3. Move the cursor to the right, past the period.
4. Now try the above steps but try backspacing without highlighting and you'll see that the period is not being deleted.

Haven't looked further yet to see if it is an edge case or symptom of something else.

**Comment by anges244** [comment]
This is now an issue again. To replicate open the Link Example, remove the link with backspace and right click to inspect the elements. It remains without a text. Is there a workaround for this?

<img width="912" alt="Screenshot 2021-04-13 at 6 50 33 PM" src="https://user-images.githubusercontent.com/3290236/114583032-dac92500-9c89-11eb-9b30-85cd14e50186.png">
