### ISSUE TITLE
`npm run benches` fails due to missing file

### ISSUE THREAD

**Issue by jfsiii** [ianstormtaylor/slate#686]
`npm run benchs` fails with the following error:

```
> slate@0.19.7 benchs /Users/jschulz/Sites/clones/slate
> babel-node ./node_modules/.bin/_matcha --reporter ./benchmark/reporter ./benchmark/index.js > ./tmp/benchmark-comparison.json && babel-node ./benchmark/compare

module.js:471
    throw err;
    ^

Error: Cannot find module '../../../../lib/constants/schema'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jschulz/Sites/clones/slate/benchmark/fixtures/transforms/normalize/index.js:2:1)
    at Module._compile (module.js:570:32)
    at loader (/Users/jschulz/Sites/clones/slate/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jschulz/Sites/clones/slate/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

It appears that #675 introduced files which reference `lib/constants/schema` but the file was not added to the repo.

**Comment by Rebulus** [comment]
@jfsiii as I understand, [here](https://github.com/ianstormtaylor/slate/blob/master/benchmark/fixtures/transforms/normalize/index.js#L2) just a mistake and right path should be:
`import SCHEMA from '../../../../lib/schemas/core'`
@ianstormtaylor am I right?

**Comment by ianstormtaylor** [comment]
@jfsiii sorry for the delay, but thanks for pointing that out. And @Rebulus yup, you're right!
