### ISSUE TITLE
Bug: Undo/Redo behaviour seemed to be bugged with Inline nodes

### ISSUE THREAD

**Issue by deep-c** [ianstormtaylor/slate#813]
#### Do you want to request a *feature* or report a *bug*?

Bug

#### What's the current behavior?
Ive run into this problem on my project at work (quite a severe problem unfortunately :( ) which I can replicate on the demo as well. Only tested my Window machine so far will check if it happens on Mac when i get the chance. (Windows 10, Chrome Version 58.0.3029.96 (64-bit)). 

1. Go to link demo[http://slatejs.org/#/links](http://slatejs.org/#/links)
2. Add a link (with or without an expanded selection)
3. Press CTRL+Z to undo (works)
4. Press CTRL+SHIFT+Z to redo (ERROR)
```
Uncaught Error: Could not find a descendant at path "1,1".
    at Document.assertPath (http://slatejs.org/build.prod.js:10074:13)
    at moveNode (http://slatejs.org/build.prod.js:18313:27)
    at Object.Transforms.applyOperation (http://slatejs.org/build.prod.js:18120:21)
    at Transform.(anonymous function) [as applyOperation] (http://slatejs.org/build.prod.js:15160:32)
    at http://slatejs.org/build.prod.js:21471:15
    at Array.forEach (native)
    at Object.Transforms.redo (http://slatejs.org/build.prod.js:21470:8)
    at Transform.(anonymous function) [as redo] (http://slatejs.org/build.prod.js:15160:32)
    at onKeyDownZ (http://slatejs.org/build.prod.js:16046:61)
    at Object.onKeyDown (http://slatejs.org/build.prod.js:15730:16)
```

#### What's the expected behavior?

Able to undo and redo Inline node insertions/removals

Thanks

**Comment by villetou** [comment]
You can replicate the issue in the slate's link example:

1. Add link via the toolbar, input address and text
2. Undo so that the link gets removed
3. Redo

The same error should be showing in the console

`Uncaught Error: Could not find a descendant at path "1,1".
    at Document.assertPath (http://slatejs.org/build.prod.js:10092:13)
    at moveNode (http://slatejs.org/build.prod.js:18336:27)
    at Object.Transforms.applyOperation (http://slatejs.org/build.prod.js:18143:21)
    at Transform.(anonymous function) [as applyOperation] (http://slatejs.org/build.prod.js:15178:32)
    at http://slatejs.org/build.prod.js:21501:15
    at Array.forEach (native)
    at Object.Transforms.redo (http://slatejs.org/build.prod.js:21500:8)
    at Transform.(anonymous function) [as redo] (http://slatejs.org/build.prod.js:15178:32)
    at onKeyDownZ (http://slatejs.org/build.prod.js:16064:61)
    at Object.onKeyDown (http://slatejs.org/build.prod.js:15748:16)`
